### ISSUE TITLE
Release Note Automation

### ISSUE THREAD

**Issue by sophiewigmore** [paketo-buildpacks/github-config#259] opened 2021-04-19 22:57 UTC
Some of our repositories have changelogs in their release notes (check out [packit's release notes](https://github.com/paketo-buildpacks/packit/releases/tag/v0.10.1) for example). This information is helpful for users, but can be time consuming for maintainers. It's also not standardized across our buildpacks and other repos.

We should create some kind of automation that will auto-generate a changelog in the release notes when the `create-draft-release` workflow runs so we can have consistent notes across our community.

**Comment by fg-j** [comment] 2021-04-22 14:09
I've noticed that since the changelog update went out to the Paketo repos, the Create/Draft release job has been failing in this way:
https://github.com/paketo-buildpacks/go/runs/2410575650
https://github.com/paketo-buildpacks/go-dist/runs/2410518137

Something is off about the YAML, perhaps...

**Comment by ryanmoran** [comment] 2021-04-22 15:23
Should be resolved by https://github.com/paketo-buildpacks/github-config/pull/263

**Comment by ryanmoran** [comment] 2021-04-22 15:57
Confirmed to be resolved by #263.

**Closed by ryanmoran** 2021-04-22 15:57 UTC
Labels: enhancement, possible-priority
